version: '3.8'

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # [수정] Certbot 볼륨을 직접 마운트합니다.
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always

  # 2. Certbot (SSL 인증서 자동 발급 및 갱신 봇)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      # [수정] Certbot 볼륨을 직접 마운트합니다.
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # 3. Backend (Go API Server)
  backend:
    image: us-central1-docker.pkg.dev/realtime-chat-project-478509/realtime-chat-repo/backend:latest
    container_name: backend
    env_file:
      - .env.prod # 운영용 환경 변수
    restart: always

  # 4. Frontend (React + Nginx Server)
  frontend:
    image: us-central1-docker.pkg.dev/realtime-chat-project-478509/realtime-chat-repo/frontend:latest
    container_name: frontend
    restart: always

  # 5. Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # env_file을 통째로 넘기는 대신, environment 섹션에서 매핑합니다.
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

# 데이터베이스 볼륨 정의
volumes:
  postgres-data:
  certbot-conf:
  certbot-www: