# 1. Deployment: 프론트엔드 컨테이너를 실행합니다.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-northeast3-docker.pkg.dev/realtime-chat-project-478509/realtime-chat-repo/frontend:latest
        ports:
        - containerPort: 80
---
# 2. Service: 프론트엔드를 외부로 노출합니다.
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # 외부 접속용 공인 IP 할당 
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80