apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 관리할 리소스 목록
resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - certificate.yaml
  - backend-config.yaml
  
# 이미지 태그 관리
images:
  - name: backend-image 
    newName: asia-northeast3-docker.pkg.dev/realtime-chat-project-478509/realtime-chat-repo/backend
    newTag: latest # 초기값 (CI가 이 값을 자동으로 변경)
  
  - name: frontend-image
    newName: asia-northeast3-docker.pkg.dev/realtime-chat-project-478509/realtime-chat-repo/frontend
    newTag: latest