# Step 1: 인증서 발급용 임시 설정
server {
    listen 80;
    server_name chat.jungyu.store;

    # Certbot이 인증을 위해 사용하는 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 나머지 모든 요청은 임시로 404를 반환.
    location / {
        return 404;
    }
}